### ISSUE TITLE
sr_model.py里有个idx变量错误

### ISSUE THREAD

**Issue by eblis88** [mjq11302010044/Real-CE#10]
Testing RealCE...
0image [00:00, ?image/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/Real-CE/basicsr/test.py", line 46, in <module>
    test_pipeline(root_path)
  File "/root/autodl-tmp/Real-CE/basicsr/test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "/root/autodl-tmp/Real-CE/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/root/autodl-tmp/Real-CE/basicsr/models/sr_model.py", line 691, in nondist_validation
    self.metric_results[metric] /= (idx + 1)
UnboundLocalError: local variable 'idx' referenced before assignment

**Comment by ZY1234-pixel** [comment]
请问你使用那个预训练模型跑的呀，作者好像没有公开net_g_100000.pth
